test:
    pytest tests
sudo: false
language: python
cache: pip
matrix:
  include:
    - python: 2.7
      env:
      - TOXENV=py27
    - python: 3.5
      env:
      - TOXENV=py35
    - python: 3.6
      env:
      - TOXENV=py36
notifications:
  email:
    recipients:
      - dxdstudio@gmail.com
    on_failure: always
    on_success: always
install:
    - pip install -U prospector
    - pip install -U coveralls
    - pip install -U tox
    - pip install -U pytest
    - pip install -U pyquery
    - python setup.py install
script: tox -e $TOXENV
after_success:
  coveralls
